<a href="https://colab.research.google.com/github/Varun-55-gvh/ML_23AG1A66D2/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#create a list named list1
list = [2,4,6,8]
array1=np.array(list)
print(array1)

[2 4 6 8]


In [ ]:
#create a 2D array with 2 rows and 4 columns
array1 = np.array ([[1,2,3,4],
 [5,6,7,8]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#create a 3D array with 2 "slices", each 0f 3 rows and 4 columns
array1 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
#create an array of integers
array1 = np.array([2,3,4])

In [ ]:
#check the data type of array1
print(array1.dtype)


int64


In [ ]:
print(array1.ndim)

1


In [ ]:
print(array1.size)

3


In [ ]:
array1 = np.array([[1,2,3],[6,7,8]])

In [ ]:
#return a tuple that give size of array in each dimension
print(array1.shape)

(2, 3)


In [ ]:
#create a default 1-D array of integers
array1 = np.array([6,7,8,10.,13])

In [ ]:
#create a 1-D array of 23-bit integers
array2 = np.array([6,7,8,10.,13], dtype=np.int32)

In [ ]:
#use of itemsize to determine size of each array element of arrasy1 and array2
print(array1.itemsize)
print(array2.itemsize)


8
4
